server:
  port: 2111
spring:
  application:
    name: hello-Customer
eureka:
  instance:
    peer1:
      hostname: peer1
      port: 1111
    peer2:
      hostname: peer2
      port: 1112
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.peer1.hostname}:${eureka.instance.peer1.port}/eureka,http://${eureka.instance.peer2.hostname}:${eureka.instance.peer2.port}/eureka