#server:
#  port: 1112
##配置服务名称
##配置注册中心的地址
#spring:
#  application:
#    name: hello-service
#eureka:
#  client:
#    instance:
#      name: localhost
#      port: 1111
#    serviceUrl:
#      defaultZone: http://${eureka.client.instance.name}:${eureka.client.instance.port}/eureka
#高可用配置
server:
  port: 1112
spring:
  application:
    name: peer2-service
eureka:
  instance:
    peer1:
      hostname: peer1
      port: 1111
    peer2:
      hostname: peer2
      port: 1112
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.peer1.hostname}:${eureka.instance.peer1.port}/eureka,http://${eureka.instance.peer2.hostname}:${eureka.instance.peer2.port}/eureka
